 EXPLAIN PLAN FOR
  SELECT "DAP_DNI","DAP_NOMBRE","DAP_APELLID","DAP_SEXO","DAP_DIR_CODIGO","DAL_DEP_CODIGO","DAL_CED_CODIGO","DAL_SED_CODIGO","DAL_ACM_CODIGO","DAL_ACP_CODIGO","DAL_CAT_CODIGO","DAL_PUF_CODIGO1","DAL_PUF_CODIGO2","DAL_PLL_CODIGO1","DAL_PLL_CODIGO2","DAL_CAA_CODIGO","DAL_SAP_CODIGO","DAL_DEP_CODIGO2","PUF_CODIGO","PUF_DESCRI","PUF_NIVEL","PUF_TIPESPEC","PUF_TIPPUES","PUF_GRU_CODIGO1","PUF_GRU_CODIGO2","PUF_OCUPA","PUF_TIPOCUPA","PUF_PRG_CODIGO","PUF_DEP_CODIGO","PUF_CED_CODIGO","PUF_FECHAVIG","PUF_FECHAFIN","PUF_NORDEN_DEPT","PUF_FIRMA","PUF_PROVISION","PUF_PERFIL","PUF_CPUF_CODIGO","PUF_DEFP_CODIGO","PUF_MODULO_HORARIO","PUF_TIPO","PUF_JORNADA","PUF_ADMINISTRACION","PUF_TITULO","PUF_OBSERVACIONES","PUF_PLL_COMPLJEF","PUF_PLL_COMPLJOR","PUF_PLL_COMPLNOC","PUF_PLL_COMPLPEL","PUF_PLL_COMPLINF","PUF_PLL_TIPOPLAZ","PUF_CUERPO","PUF_PLL_CARGO","PUF_SIT_PRESUPUES","PUF_DED_CODIGO","PUF_TIPESPEC2","PUF_MERITO_TITG","PUF_SAPR_CODIGO","PUF_DIR_CODIGO","PUF_VICERRECTORADO","PUF_RESPONS_INE","PUF_EPS_CODIGO","PUF_MARCA","PUF_TELEFONO","PUF_PRG_CODIGO2","PUF_OCU_CODIGO","PUF_MUNI","PUF_DEP_PERFIL","DEP_CODIGO","DEP_CODIGO_MEC","DEP_NOMBRE","DEP_NOMBRE_CORTO","DEP_DOCENTE","DEP_DESAPARECIDO","DEP_ESP_TIPO","DEP_ESP_CODIGO","DEP_AREALEY","DEP_FECHA_CREACION","DEP_FECHA_DESAPARICION","DEP_LISTA_EMAIL","DEP_LISTA_EMAIL_PAS","DEP_HIST_CODIGO","DEP_ESTRUCTURA","DEP_VIC_CODIGO","DEP_NUM_ORDEN","DEP_CAA_CODIGO","DEP_CED_CODIGO","DEP_TIDE_CODIGO","DEP_NIVEL_LDAP"
FROM PERSONAL_ACTIVO, PUESTO_FUNCIONARIOS, departamentos
WHERE (DAL_PUF_CODIGO1 = PUF_CODIGO OR DAL_PUF_CODIGO2 = PUF_CODIGO OR DAL_PLL_CODIGO1 = PUF_CODIGO OR DAL_PLL_CODIGO1 = PUF_CODIGO)
AND PUF_FECHAFIN = TO_DATE('31123999', 'DDMMYYYY')
AND PUF_DEFP_CODIGO = '15'
and dep_codigo = dal_dep_codigo
and dep_docente = 'S' ;

/
 EXPLAIN PLAN FOR
SELECT "DAP_DNI","DAP_NOMBRE","DAP_APELLID","DAP_SEXO","DAP_DIR_CODIGO","DAL_DEP_CODIGO","DAL_CED_CODIGO","DAL_SED_CODIGO","DAL_ACM_CODIGO","DAL_ACP_CODIGO","DAL_CAT_CODIGO","DAL_PUF_CODIGO1","DAL_PUF_CODIGO2","DAL_PLL_CODIGO1","DAL_PLL_CODIGO2","DAL_CAA_CODIGO","DAL_SAP_CODIGO","DAL_DEP_CODIGO2","PUF_CODIGO","PUF_DESCRI","PUF_NIVEL","PUF_TIPESPEC","PUF_TIPPUES","PUF_GRU_CODIGO1","PUF_GRU_CODIGO2","PUF_OCUPA","PUF_TIPOCUPA","PUF_PRG_CODIGO","PUF_DEP_CODIGO","PUF_CED_CODIGO","PUF_FECHAVIG","PUF_FECHAFIN","PUF_NORDEN_DEPT","PUF_FIRMA","PUF_PROVISION","PUF_PERFIL","PUF_CPUF_CODIGO","PUF_DEFP_CODIGO","PUF_MODULO_HORARIO","PUF_TIPO","PUF_JORNADA","PUF_ADMINISTRACION","PUF_TITULO","PUF_OBSERVACIONES","PUF_PLL_COMPLJEF","PUF_PLL_COMPLJOR","PUF_PLL_COMPLNOC","PUF_PLL_COMPLPEL","PUF_PLL_COMPLINF","PUF_PLL_TIPOPLAZ","PUF_CUERPO","PUF_PLL_CARGO","PUF_SIT_PRESUPUES","PUF_DED_CODIGO","PUF_TIPESPEC2","PUF_MERITO_TITG","PUF_SAPR_CODIGO","PUF_DIR_CODIGO","PUF_VICERRECTORADO","PUF_RESPONS_INE","PUF_EPS_CODIGO","PUF_MARCA","PUF_TELEFONO","PUF_PRG_CODIGO2","PUF_OCU_CODIGO","PUF_MUNI","PUF_DEP_PERFIL","DEP_CODIGO","DEP_CODIGO_MEC","DEP_NOMBRE","DEP_NOMBRE_CORTO","DEP_DOCENTE","DEP_DESAPARECIDO","DEP_ESP_TIPO","DEP_ESP_CODIGO","DEP_AREALEY","DEP_FECHA_CREACION","DEP_FECHA_DESAPARICION","DEP_LISTA_EMAIL","DEP_LISTA_EMAIL_PAS","DEP_HIST_CODIGO","DEP_ESTRUCTURA","DEP_VIC_CODIGO","DEP_NUM_ORDEN","DEP_CAA_CODIGO","DEP_CED_CODIGO","DEP_TIDE_CODIGO","DEP_NIVEL_LDAP"
FROM PERSONAL_ACTIVO pa, PUESTO_FUNCIONARIOS pf, departamentos
WHERE pf.PUF_CODIGO IN (
   pa.DAL_PUF_CODIGO1,
   pa.DAL_PUF_CODIGO2,
   pa.DAL_PLL_CODIGO1,
   pa.DAL_PLL_CODIGO2)
AND PUF_FECHAFIN = TO_DATE('31123999', 'DDMMYYYY')
AND PUF_DEFP_CODIGO = '15'
and dep_codigo = dal_dep_codigo
and dep_docente = 'S' ;

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);  


EXPLAIN PLAN FOR
WITH puestos_filtrados AS (
    SELECT 
        puf.PUF_CODIGO,
        puf.PUF_DEFP_CODIGO,
        puf.PUF_FECHAVIG,
        puf.PUF_FECHAFIN,
        puf.PUF_CED_CODIGO,
        puf.PUF_DEP_CODIGO,
        puf.PUF_DIR_CODIGO,
        puf.PUF_OCUPA,
        puf.PUF_NIVEL,
        d.DEP_CODIGO,
        d.DEP_NOMBRE,
        d.DEP_DOCENTE
    FROM PUESTO_FUNCIONARIOS puf
    JOIN DEPARTAMENTOS d
        ON d.DEP_CODIGO = puf.PUF_DEP_CODIGO
    WHERE puf.PUF_FECHAFIN = DATE '3999-12-31'
      AND puf.PUF_DEFP_CODIGO = '15'
      AND d.DEP_DOCENTE = 'S'
)
SELECT DISTINCT
    pa.*,
    pf.*
FROM PERSONAL_ACTIVO pa
JOIN puestos_filtrados pf
    ON pa.DAL_PUF_CODIGO1 = pf.PUF_CODIGO

UNION ALL
SELECT DISTINCT
    pa.*,
    pf.*
FROM PERSONAL_ACTIVO pa
JOIN puestos_filtrados pf
    ON pa.DAL_PUF_CODIGO2 = pf.PUF_CODIGO

UNION ALL
SELECT DISTINCT
    pa.*,
    pf.*
FROM PERSONAL_ACTIVO pa
JOIN puestos_filtrados pf
    ON pa.DAL_PLL_CODIGO1 = pf.PUF_CODIGO

UNION ALL
SELECT DISTINCT
    pa.*,
    pf.*
FROM PERSONAL_ACTIVO pa
JOIN puestos_filtrados pf
    ON pa.DAL_PLL_CODIGO2 = pf.PUF_CODIGO;
/
EXPLAIN PLAN FOR
WITH puestos_filtrados AS (
    SELECT 
        puf.PUF_CODIGO,
        puf.PUF_DEFP_CODIGO,
        puf.PUF_FECHAFIN,
        d.DEP_CODIGO
    FROM PUESTO_FUNCIONARIOS puf
    JOIN DEPARTAMENTOS d
        ON d.DEP_CODIGO = puf.PUF_DEP_CODIGO
    WHERE puf.PUF_FECHAFIN = DATE '3999-12-31'
      AND puf.PUF_DEFP_CODIGO = '15'
      AND d.DEP_DOCENTE = 'S'
),
dni_filtrado AS (
    SELECT DISTINCT hdl_dap_dni AS dni
    FROM historico_datos_laborales h
    JOIN puestos_filtrados pf
         ON SUBSTR(h.hdl_valor_del_campo, 1, 7) = pf.PUF_CODIGO
    WHERE h.hdl_tca_codigo IN (
            'DAL_PUF_CODIGO1',
            'DAL_PUF_CODIGO2',
            'DAL_PLL_CODIGO1',
            'DAL_PLL_CODIGO2'
        )
      AND h.hdl_fechaini <= TRUNC(SYSDATE)
      AND h.hdl_fechafin >= TRUNC(SYSDATE)
)
SELECT pa.*, pf.*
FROM PERSONAL_ACTIVO pa
JOIN dni_filtrado f
    ON f.dni = pa.DAP_DNI
JOIN puestos_filtrados pf
    ON pf.PUF_CODIGO IN (
        pa.DAL_PUF_CODIGO1,
        pa.DAL_PUF_CODIGO2,
        pa.DAL_PLL_CODIGO1,
        pa.DAL_PLL_CODIGO2
    );
    
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY); 
