-- Como SYS, crear directorio virtual
CREATE OR REPLACE DIRECTORY ARCHIVOS_DIR AS '/opt/oracle/archivos';

-- Dar permisos al usuario
GRANT READ, WRITE  ON DIRECTORY ARCHIVOS_DIR TO C##DEVUSER1;
GRANT READ, WRITE  ON DIRECTORY ARCHIVOS_DIR TO C##DEVUSER2;
