--Crear tablas:

CREATE TABLE clientes (
    cliente_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL
);

CREATE TABLE pedidos (
    pedido_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id NUMBER,
    fecha DATE DEFAULT SYSDATE,
    CONSTRAINT fk_pedidos_clientes
        FOREIGN KEY (cliente_id)
        REFERENCES clientes (cliente_id)
);


--Insertar datos:

INSERT INTO clientes (nombre) VALUES ('Laura');
INSERT INTO pedidos (cliente_id) VALUES (1);
INSERT INTO pedidos (cliente_id) VALUES (99); -- ERROR: no existe el cliente 99


--Consultar las restricciones creadas:

SELECT constraint_name, constraint_type, status
FROM user_constraints
WHERE table_name IN ('CLIENTES', 'PEDIDOS');


--Crear un índice en la clave foránea:

CREATE INDEX idx_pedidos_cliente ON pedidos (cliente_id);
