--Crear tabla:

CREATE TABLE empleados (
    empleado_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100),
    departamento_id NUMBER,
    salario NUMBER
);


--Crear índices:

CREATE INDEX idx_emp_nombre ON empleados (nombre);
CREATE INDEX idx_emp_depto_salario ON empleados (departamento_id, salario);
CREATE BITMAP INDEX idx_emp_depto_bitmap ON empleados (departamento_id);

--Analizar el uso:

--EXPLAIN PLAN FOR
SELECT * FROM empleados WHERE departamento_id = 10 AND salario > 2000;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);


--Eliminar un índice redundante:

DROP INDEX idx_emp_depto_bitmap;
