--------------------------------------------------------------------------------
-- SCRIPT: ejemplos_avanzados_check_constraints.sql
-- OBJETIVO: Demostrar uso avanzado de restricciones CHECK en Oracle Database
-- AUTOR: ChatGPT
-- COMPATIBLE CON: Oracle 12c en adelante
--------------------------------------------------------------------------------

-- Limpieza previa (por si existen versiones anteriores)
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE empleados CHECKPOINT PURGE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE usuarios_func CHECKPOINT PURGE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP FUNCTION es_email_valido';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
--------------------------------------------------------------------------------
--  TABLA CON CHECKS BÁSICOS (rangos y listas)
--------------------------------------------------------------------------------
CREATE TABLE empleados (
    empleado_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      VARCHAR2(100) NOT NULL,
    edad        NUMBER,
    salario     NUMBER,
    categoria   VARCHAR2(20),
    CONSTRAINT chk_edad CHECK (edad BETWEEN 18 AND 65),
    CONSTRAINT chk_salario CHECK (salario >= 1200),
    CONSTRAINT chk_categoria CHECK (categoria IN ('JUNIOR', 'SENIOR', 'LEAD'))
);

PROMPT ==== Insertando datos en EMPLEADOS (algunos válidos y otros inválidos) ====

INSERT INTO empleados (nombre, edad, salario, categoria)
VALUES ('Laura', 30, 2000, 'SENIOR');  -- OK

-- Este fallará: edad fuera de rango
BEGIN
    INSERT INTO empleados (nombre, edad, salario, categoria)
    VALUES ('Pedro', 70, 1500, 'JUNIOR');
EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error esperado: ' || SQLERRM);
END;
/

-- Este fallará: categoría inválida
BEGIN
    INSERT INTO empleados (nombre, edad, salario, categoria)
    VALUES ('Marta', 40, 1800, 'BECARIO');
EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error esperado: ' || SQLERRM);
END;
/

--------------------------------------------------------------------------------
--  TABLA CON CHECK USANDO REGEXP_LIKE (validación de email)
--------------------------------------------------------------------------------
CREATE TABLE usuarios (
    usuario_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR2(100) NOT NULL,
    CONSTRAINT chk_email_regex CHECK (
        REGEXP_LIKE(email, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$')
    )
);

PROMPT ==== Insertando datos en USUARIOS ====

INSERT INTO usuarios (email) VALUES ('juan.perez@example.com');  -- OK

BEGIN
    INSERT INTO usuarios (email) VALUES ('juan@mal_email');  -- ERROR
EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error esperado: ' || SQLERRM);
END;
/

--------------------------------------------------------------------------------
-- UNCIÓN PERSONALIZADA + CHECK CON FUNCIÓN DETERMINISTIC
--------------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION es_email_valido(p_email VARCHAR2)
RETURN NUMBER DETERMINISTIC IS
BEGIN
    IF REGEXP_LIKE(p_email, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$') THEN
        RETURN 1;
    ELSE
        RETURN 0;
    END IF;
END;
/

CREATE TABLE usuarios_func (
    usuario_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR2(100) NOT NULL,
    CONSTRAINT chk_email_func CHECK (es_email_valido(email) = 1)
);

 ==== Insertando datos en USUARIOS_FUNC ====

INSERT INTO usuarios_func (email) VALUES ('sofia@dominio.com');  -- OK

BEGIN
    INSERT INTO usuarios_func (email) VALUES ('sofia@dominio');  -- ERROR
EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error esperado: ' || SQLERRM);
END;
/

--------------------------------------------------------------------------------
-- ALTER TABLE: DESACTIVAR, ELIMINAR Y RECREAR CHECKS
--------------------------------------------------------------------------------
 ==== Desactivando y reactivando un CHECK en EMPLEADOS ====

ALTER TABLE empleados DISABLE CONSTRAINT chk_categoria;

-- Ahora se puede insertar un valor fuera de la lista
INSERT INTO empleados (nombre, edad, salario, categoria)
VALUES ('Carlos', 35, 2500, 'OTRO');  -- OK (check deshabilitado)

ALTER TABLE empleados ENABLE CONSTRAINT chk_categoria;  -- Reactivar

 ==== Eliminando y recreando un CHECK ====

ALTER TABLE empleados DROP CONSTRAINT chk_salario;

-- Intentar insertar salario negativo (ya no se valida)
INSERT INTO empleados (nombre, edad, salario, categoria)
VALUES ('Diego', 40, -100, 'SENIOR');  -- Permitido

-- Volvemos a crear el CHECK correctamente
ALTER TABLE empleados ADD CONSTRAINT chk_salario CHECK (salario > 0);

--------------------------------------------------------------------------------
-- CONSULTA FINAL: MOSTRAR TODAS LAS RESTRICCIONES DEFINIDAS
--------------------------------------------------------------------------------
==== Restricciones definidas por el usuario ====

COLUMN table_name FORMAT A20
COLUMN constraint_name FORMAT A30
COLUMN constraint_type FORMAT A5
COLUMN search_condition FORMAT A60 WORD_WRAP

SELECT table_name, constraint_name, constraint_type, search_condition
FROM user_constraints
WHERE table_name IN ('EMPLEADOS', 'USUARIOS', 'USUARIOS_FUNC')
ORDER BY table_name, constraint_name;

--------------------------------------------------------------------------------
-- FIN DEL SCRIPT
--------------------------------------------------------------------------------


